# Generated by Django 3.1.12 on 2023-03-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('author', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=20)),
            ],
        ),
    ]
